# grunt task aliases configuration

default:
  - 'build'

build:
  - 'clean'
  - 'copy'
  - 'less'
  - 'html2js'
  - 'injector'

compile:
  - 'build'
  - 'useminPrepare'
  - 'concat:generated'
  - 'ngAnnotate'
  - 'uglify:generated'
  - 'usemin'
  - 'clean:compile'

develop:
  - 'build'
  - 'concurrent:dev'

launch:
  - 'compile'
  - 'nodemon'
