# grunt copy task config

manifest:
  files:
    - expand: true
      cwd: 'src'
      src:
        - 'index.html'
      dest: 'public'

app:
  files:
    - expand: true
      cwd: 'src'
      src:
        - '**/*.js'
        - '!vendor/**/*'
      dest: 'public'

vendor:
  files:
    - expand: true
      cwd: 'src'
      src:
        - 'vendor/**/*'
      dest: public
