# grunt injector task config

app:
  options:
    starttag: '<!-- inject:app:{{ext}} -->'
    endtag: '<!-- endinject -->'
    destFile: 'public/index.html'
    ignorePath: 'public/'
  files:
    src:
      - 'public/app.js'
      - 'public/app/**/*.js'
      - 'public/assets/**/*.css'

bower:
  options:
    starttag: '<!-- inject:vendor:{{ext}} -->'
    endtag: '<!-- endinject -->'
    destFile: 'public/index.html'
    ignorePath: 'src/'
  files:
    src:
      - 'bower.json'
